package com.example.timetonicapp.model

/**
 * Data class representing the response from the appKey API.
 * Properties: appkey - The appkey generated by the server.
 *             errorMsg - The possible error message.
 */
data class AppKeyResponse(
    val appkey: String,
    val errorMsg: String
)
