package com.example.timetonicapp.model

/**
 * Data class representing the response from the oauthKey API.
 * Properties: oauthkey - The oauthkey generated by the server.
 *             o_u - The user o_u associated with the oauthkey.
 */
data class OauthKeyResponse(
    val oauthkey: String,
    val o_u: String
)