package com.example.timetonicapp.model

/**
 * Data class representing the response from the sessKey API.
 * Properties: sesskey - The sesskey generated by the server.
 */
data class SessKeyResponse(val sesskey: String)
